#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	--exclude subscribers \
	. 'wahlrecht-bot:~/wahlrecht-bot/'

ssh wahlrecht-bot "\
cd ~/wahlrecht-bot
npm i
npm update
forever stop wahlrecht-bot
export NODE_ENV=production
forever start -a --uid wahlrecht-bot index.js"